metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/metricbeat/logs
  name: metricbeat
  keepfiles: 7
  permissions: 0644
